"""Add missing columns

Revision ID: 7adf02fc54e3
Revises: 
Create Date: 2026-09-26 23:07:44.309742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adf02fc54e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only applying experiences and trips missing columns

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_reasoning', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('day_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_trips_destination_id', 'destinations', ['destination_id'], ['id'])

    # ### end Alembic commands ###
    
    # Custom Backfill
    bind = op.get_bind()
    import json
    trips = bind.execute(sa.text("SELECT id, preferences FROM trips")).fetchall()
    for trip in trips:
        trip_id, prefs_json = trip
        if prefs_json:
            try:
                prefs = json.loads(prefs_json)
                if isinstance(prefs, dict) and "destination_id" in prefs:
                    dest_id = prefs["destination_id"]
                    bind.execute(
                        sa.text("UPDATE trips SET destination_id = :dest_id WHERE id = :trip_id"),
                        {"dest_id": dest_id, "trip_id": trip_id}
                    )
            except Exception:
                pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_column('destination_id')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('day_date')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('ai_reasoning')
        batch_op.drop_column('estimated_cost')

    with op.batch_alter_table('disruptions', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_column('requires_approval')
        batch_op.drop_column('confidence')
        batch_op.drop_column('impact_summary')
        batch_op.drop_column('current_value')
        batch_op.drop_column('previous_value')
        batch_op.drop_column('source_record_id')
        batch_op.drop_column('source')
        batch_op.drop_column('title')
        batch_op.drop_column('severity')
        batch_op.drop_column('disruption_type')
        batch_op.drop_column('itinerary_version_id')

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('preferences',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('vendor_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.create_foreign_key(None, 'vendors', ['vendor_id'], ['id'])
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('cancellation_policy')
        batch_op.drop_column('source_type')
        batch_op.drop_column('provider_reference')
        batch_op.drop_column('currency')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('location')
        batch_op.drop_column('end_datetime')
        batch_op.drop_column('start_datetime')
        batch_op.drop_column('booking_type')
        batch_op.drop_column('provider_id')
        batch_op.drop_column('traveler_id')
        batch_op.drop_column('itinerary_item_id')

    with op.batch_alter_table('alternative_plans', schema=None) as batch_op:
        batch_op.drop_column('items')
        batch_op.drop_column('reason')
        batch_op.drop_column('travel_time_difference')
        batch_op.drop_column('preference_match')
        batch_op.drop_column('cost_difference')

    # ### end Alembic commands ###
